In [2]:
import pandas as pd
import numpy as np
import os
import datetime
from  __future__ import division

In [1]:
airport_data = pd.read_csv('../../Datasets/airports.csv', delimiter=',')
airlines_data = pd.read_csv('../../Datasets/airlines.csv', delimiter=',')
print "Completed Processing"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Completed Processing")? (<ipython-input-1-35e44227d73f>, line 3)

In [3]:
data = pd.read_csv('../../Datasets/flights.csv', delimiter=',', low_memory=False)
print "Completed Processing"
print data.shape

Completed Processing
(5819079, 31)

In [17]:
data['SCHEDULED_DEPARTURE'].head(100)

0       5
1      10
2      20
3      20
4      25
5      25
6      25
7      30
8      30
9      30
10     30
11     35
12     35
13     40
14     40
15     45
16     45
17     48
18     50
19     50
20     55
21    100
22    103
23    105
24    105
25    115
26    115
27    115
28    120
29    120
     ...
70    515
71    515
72    515
73    520
74    520
75    520
76    520
77    520
78    520
79    520
80    523
81    525
82    525
83    530
84    530
85    530
86    530
87    530
88    530
89    530
90    530
91    530
92    531
93    533
94    535
95    535
96    535
97    535
98    535
99    535
Name: SCHEDULED_DEPARTURE, Length: 100, dtype: int64

In [4]:
print data.columns.values

['YEAR' 'MONTH' 'DAY' 'DAY_OF_WEEK' 'AIRLINE' 'FLIGHT_NUMBER' 'TAIL_NUMBER'
 'ORIGIN_AIRPORT' 'DESTINATION_AIRPORT' 'SCHEDULED_DEPARTURE'
 'DEPARTURE_TIME' 'DEPARTURE_DELAY' 'TAXI_OUT' 'WHEELS_OFF'
 'SCHEDULED_TIME' 'ELAPSED_TIME' 'AIR_TIME' 'DISTANCE' 'WHEELS_ON'
 'TAXI_IN' 'SCHEDULED_ARRIVAL' 'ARRIVAL_TIME' 'ARRIVAL_DELAY' 'DIVERTED'
 'CANCELLED' 'CANCELLATION_REASON' 'AIR_SYSTEM_DELAY' 'SECURITY_DELAY'
 'AIRLINE_DELAY' 'LATE_AIRCRAFT_DELAY' 'WEATHER_DELAY']

In [5]:
#Conversion of Day, Year, Month to DATE
data['FLIGHT_DATE'] = pd.to_datetime(data[['YEAR','MONTH','DAY']])
print "COMPLETED"
print data.shape

COMPLETED
(5819079, 32)

In [6]:
dataDict = pd.DataFrame({'DataType': data.dtypes.values, 'Missing_values': data.isnull().sum(),'Missing%': ((data.isnull().sum())/(data.shape[0])*100)  }, index=data.columns.values)
dataDict

                           DataType   Missing%  Missing_values
YEAR                          int64   0.000000               0
MONTH                         int64   0.000000               0
DAY                           int64   0.000000               0
DAY_OF_WEEK                   int64   0.000000               0
AIRLINE                      object   0.000000               0
FLIGHT_NUMBER                 int64   0.000000               0
TAIL_NUMBER                  object   0.252978           14721
ORIGIN_AIRPORT               object   0.000000               0
DESTINATION_AIRPORT          object   0.000000               0
SCHEDULED_DEPARTURE           int64   0.000000               0
DEPARTURE_TIME              float64   1.480526           86153
DEPARTURE_DELAY             float64   1.480526           86153
TAXI_OUT                    float64   1.530259           89047
WHEELS_OFF                  float64   1.530259           89047
SCHEDULED_TIME              float64   0.000103               6
ELAPSED_TIME                float64   1.805629          105071
AIR_TIME                    float64   1.805629          105071
DISTANCE                      int64   0.000000               0
WHEELS_ON                   float64   1.589822           92513
TAXI_IN                     float64   1.589822           92513
SCHEDULED_ARRIVAL             int64   0.000000               0
ARRIVAL_TIME                float64   1.589822           92513
ARRIVAL_DELAY               float64   1.805629          105071
DIVERTED                      int64   0.000000               0
CANCELLED                     int64   0.000000               0
CANCELLATION_REASON          object  98.455357         5729195
AIR_SYSTEM_DELAY            float64  81.724960         4755640
SECURITY_DELAY              float64  81.724960         4755640
AIRLINE_DELAY               float64  81.724960         4755640
LATE_AIRCRAFT_DELAY         float64  81.724960         4755640
WEATHER_DELAY               float64  81.724960         4755640
FLIGHT_DATE          datetime64[ns]   0.000000               0

In [7]:
#data = data.drop(['FLIGHT_NUMBER','YEAR','MONTH','DAY','TAIL_NUMBER','TAXI_OUT','WHEELS_OFF','WHEELS_ON','TAXI_IN','WEATHER_DELAY','AIR_SYSTEM_DELAY','SECURITY_DELAY','AIRLINE_DELAY','LATE_AIRCRAFT_DELAY'], axis=1)
data = data.drop(['FLIGHT_NUMBER','DISTANCE_BINS','CANCELLATION_REASON','DIVERTED'])
print "DONE"

ValueError: labels ['FLIGHT_NUMBER' 'DISTANCE_BINS' 'CANCELLATION_REASON' 'DIVERTED'] not contained in axis

In [8]:
print data.shape

(5819079, 32)

In [23]:
data['SCHEDULED_DEPARTURE'].head(100)

0     00:05:00
1     00:10:00
2     00:20:00
3     00:20:00
4     00:25:00
5     00:25:00
6     00:25:00
7     00:30:00
8     00:30:00
9     00:30:00
10    00:30:00
11    00:35:00
12    00:35:00
13    00:40:00
14    00:40:00
15    00:45:00
16    00:45:00
17    00:48:00
18    00:50:00
19    00:50:00
20    00:55:00
21    01:00:00
22    01:03:00
23    01:05:00
24    01:05:00
25    01:15:00
26    01:15:00
27    01:15:00
28    01:20:00
29    01:20:00
        ...
70    05:15:00
71    05:15:00
72    05:15:00
73    05:20:00
74    05:20:00
75    05:20:00
76    05:20:00
77    05:20:00
78    05:20:00
79    05:20:00
80    05:23:00
81    05:25:00
82    05:25:00
83    05:30:00
84    05:30:00
85    05:30:00
86    05:30:00
87    05:30:00
88    05:30:00
89    05:30:00
90    05:30:00
91    05:30:00
92    05:31:00
93    05:33:00
94    05:35:00
95    05:35:00
96    05:35:00
97    05:35:00
98    05:35:00
99    05:35:00
Name: SCHEDULED_DEPARTURE, Length: 100, dtype: object

In [18]:
def get_time(time):
    if pd.isnull(time):
        np.nan
    else:
        h = int(time/100)
        if h == 24:
            h = 0

        m = int(time)%100
        modified_time = datetime.time(h,m)
        return modified_time

In [19]:
data['SCHEDULED_DEPARTURE'] = data['SCHEDULED_DEPARTURE'].apply(lambda x: get_time(x))
data['DEPARTURE_TIME'] = data['DEPARTURE_TIME'].apply(lambda x: get_time(x))
data['ARRIVAL_TIME'] = data['ARRIVAL_TIME'].apply(lambda x: get_time(x))
data['SCHEDULED_ARRIVAL'] = data['SCHEDULED_ARRIVAL'].apply(lambda x: get_time(x))


print "Completed"
print data.shape

Completed
(5819079, 32)

In [20]:
#Removing numeric values in ORIGIN and DESTINATION airports
print data.shape
data = data[data.ORIGIN_AIRPORT.str.isnumeric() == False]
print data.shape
#data = data[data.DESTINATION_AIRPORT.str.isnumeric() == False]

(5819079, 32)
(5332914, 32)

In [ ]:
data.to_csv ('C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis\\data.csv')

In [21]:
data.loc[:,['DEPARTURE_DELAY','ARRIVAL_DELAY']].head(30)

    DEPARTURE_DELAY  ARRIVAL_DELAY
0             -11.0          -22.0
1              -8.0           -9.0
2              -2.0            5.0
3              -5.0           -9.0
4              -1.0          -21.0
5              -5.0            8.0
6              -6.0          -17.0
7              14.0          -10.0
8             -11.0          -13.0
9               3.0          -15.0
10             -6.0          -30.0
11             -8.0          -10.0
12              0.0           -4.0
13             -6.0          -22.0
14             -1.0            8.0
15             -4.0          -14.0
16            -14.0          -24.0
17             -6.0           -7.0
18             -4.0          -18.0
19             -5.0          -12.0
20             25.0            6.0
21             -8.0            1.0
22             -1.0           -1.0
23             -2.0          -12.0
24             -3.0          -23.0
25             -3.0          -11.0
26             -8.0           -3.0
27             12.0           25.0
28            -10.0          -31.0
29             21.0            2.0

In [24]:
# Percentage of cancelled flights
(data[data.CANCELLATION_REASON.isnull() == False].DIVERTED.count())/(data.DIVERTED.count())

0.016394414010801599

In [27]:
#airline vs arrival delay
FLIGHT_ARR_DELAY_METRIC = data.loc[data['ARRIVAL_DELAY']>15,['AIRLINE','ARRIVAL_DELAY']].groupby(['AIRLINE']).agg(['count','mean','median'])
FLIGHT_ARR_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY','MEDIAN_DELAY']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['AIRLINE','ARRIVAL_DELAY']].groupby(['AIRLINE']).count().rename(columns={"ARRIVAL_DELAY":"TOTAL_FLIGHTS"})



FLIGHT_ARR_DELAY_METRIC = pd.merge(FLIGHT_ARR_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
FLIGHT_ARR_DELAY_METRIC['PERCENTAGE_DELAYED'] = (FLIGHT_ARR_DELAY_METRIC.TOTAL_DELAY_COUNT/FLIGHT_ARR_DELAY_METRIC.TOTAL_FLIGHTS)*100
FLIGHT_ARR_DELAY_METRIC
#FLIGHT_ARR_DELAY_METRIC.to_csv('C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis\\AirlineVSArrivalDelay.csv')

,TOTAL_DELAY_COUNT,MEAN_DELAY,MEDIAN_DELAY,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
AIRLINE,,,,,
AA,115542,62.093204,38.0,636554,18.151170
AS,19615,50.331991,32.0,157025,12.491641
B6,53405,63.132310,43.0,240304,22.223933
DL,107560,63.497546,37.0,794817,13.532675
EV,98932,64.797325,41.0,509621,19.412858
F9,21711,69.587859,43.0,82005,26.475215
HA,7489,41.578048,26.0,69815,10.726921
MQ,56431,64.425546,43.0,257130,21.946486
NK,31100,65.292315,44.0,105059,29.602414
OO,97514,62.438368,41.0,528328,18.457095
UA,96065,66.464154,43.0,462086,20.789420
US,34930,51.926138,34.0,194223,17.984482
VX,10497,57.857483,39.0,55813,18.807446
WN,215470,53.945412,36.0,1138350,18.928273

In [41]:
arr_del_bool_mask1 = data['ARRIVAL_DELAY']>15
arr_del_bool_mask2 = data['ARRIVAL_DELAY']<=60

In [42]:
#airline vs arrival delay
FLIGHT_ARR_DELAY_METRIC = data.loc[arr_del_bool_mask1 & arr_del_bool_mask2,['AIRLINE','ARRIVAL_DELAY']].groupby(['AIRLINE']).agg(['count','mean','median'])
FLIGHT_ARR_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY','MEDIAN_DELAY']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['AIRLINE','ARRIVAL_DELAY']].groupby(['AIRLINE']).count().rename(columns={"ARRIVAL_DELAY":"TOTAL_FLIGHTS"})



FLIGHT_ARR_DELAY_METRIC = pd.merge(FLIGHT_ARR_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
FLIGHT_ARR_DELAY_METRIC['PERCENTAGE_DELAYED'] = (FLIGHT_ARR_DELAY_METRIC.TOTAL_DELAY_COUNT/FLIGHT_ARR_DELAY_METRIC.TOTAL_FLIGHTS)*100
FLIGHT_ARR_DELAY_METRIC
#FLIGHT_ARR_DELAY_METRIC.to_csv('C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis\\AirlineVSArrivalDelay.csv')

,TOTAL_DELAY_COUNT,MEAN_DELAY,MEDIAN_DELAY,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
AIRLINE,,,,,
AA,80176,31.274596,28.0,636554,12.595318
AS,14999,29.801453,26.0,157025,9.551982
B6,34878,32.231951,29.0,240304,14.514115
DL,74425,30.745610,28.0,794817,9.363791
EV,64761,31.674912,29.0,509621,12.707679
F9,14009,32.047113,29.0,82005,17.083105
HA,6458,27.485909,24.0,69815,9.250161
MQ,36868,32.723609,30.0,257130,14.338272
NK,19699,32.460074,30.0,105059,18.750416
OO,65024,31.650591,29.0,528328,12.307506
UA,61787,31.977859,29.0,462086,13.371320
US,26103,30.567444,27.0,194223,13.439706
VX,7290,31.773525,29.0,55813,13.061473
WN,156575,31.170423,28.0,1138350,13.754557

In [52]:
#airline vs departure delay
FLIGHT_DEP_DELAY_METRIC = data.loc[data['DEPARTURE_DELAY']>0,['AIRLINE','DEPARTURE_DELAY']].groupby(['AIRLINE']).agg(['count','mean'])
FLIGHT_DEP_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['AIRLINE','DEPARTURE_DELAY']].groupby(['AIRLINE']).count().rename(columns={"DEPARTURE_DELAY":"TOTAL_FLIGHTS"})



FLIGHT_DEP_DELAY_METRIC = pd.merge(FLIGHT_DEP_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
FLIGHT_DEP_DELAY_METRIC['PERCENTAGE_DELAYED'] = (FLIGHT_DEP_DELAY_METRIC.TOTAL_DELAY_COUNT/FLIGHT_DEP_DELAY_METRIC.TOTAL_FLIGHTS)*100
FLIGHT_DEP_DELAY_METRIC
#FLIGHT_DEP_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
AIRLINE,,,,
AA,223984,34.865432,639002,35.052159
AS,40404,26.261534,157472,25.657895
B6,93718,38.457564,241056,38.878103
DL,263460,30.183629,796638,33.071483
EV,159040,41.100528,512032,31.060559
F9,32678,45.437420,82201,39.753774
HA,18446,17.070096,69889,26.393281
MQ,89272,40.321859,258555,34.527277
NK,48478,42.567350,105301,46.037550
OO,160291,39.574992,530501,30.215023
UA,239446,33.031301,463756,51.631893
US,62565,28.500615,194825,32.113435
VX,21431,30.588447,55944,38.307951
WN,527303,27.413756,1141928,46.176554

In [53]:
#Origin Airport vs Arrival Delay
AIRPORT_ARR_DELAY_METRIC = data.loc[data['ARRIVAL_DELAY']>0,['ORIGIN_AIRPORT','ARRIVAL_DELAY']].groupby(['ORIGIN_AIRPORT']).agg(['count','mean'])
AIRPORT_ARR_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['ORIGIN_AIRPORT','ARRIVAL_DELAY']].groupby(['ORIGIN_AIRPORT']).count().rename(columns={"ARRIVAL_DELAY":"TOTAL_FLIGHTS"})



AIRPORT_ARR_DELAY_METRIC = pd.merge(AIRPORT_ARR_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
AIRPORT_ARR_DELAY_METRIC['PERCENTAGE_DELAYED'] = (AIRPORT_ARR_DELAY_METRIC.TOTAL_DELAY_COUNT/AIRPORT_ARR_DELAY_METRIC.TOTAL_FLIGHTS)*100
AIRPORT_ARR_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
ORIGIN_AIRPORT,,,,
ABE,826,36.483051,2227,37.090256
ABI,686,39.295918,2231,30.748543
ABQ,6965,31.850826,18918,36.816788
ABR,246,42.211382,663,37.104072
ABY,309,37.530744,866,35.681293
ACK,162,56.061728,485,33.402062
ACT,466,43.686695,1538,30.299090
ACV,449,45.271715,1268,35.410095
ACY,1433,37.439637,3527,40.629430
ADK,56,26.053571,88,63.636364
ADQ,160,21.575000,437,36.613272
AEX,1178,41.398132,3054,38.572364
AGS,1004,31.844622,2345,42.814499
AKN,32,16.812500,63,50.793651
ALB,2006,34.900299,7322,27.396886
ALO,172,41.470930,581,29.604131
AMA,1514,34.056803,4074,37.162494
ANC,5196,23.359315,15818,32.848653
APN,142,46.528169,546,26.007326
ASE,1464,50.104508,3263,44.866687
ATL,114872,31.051240,343506,33.441046
ATW,1076,32.697026,2759,38.999638
AUS,14681,34.072202,41392,35.468206
AVL,933,39.449089,2673,34.904602
AVP,463,40.449244,1326,34.917044
AZO,498,39.491968,1743,28.571429
BDL,5691,34.367071,18375,30.971429
BET,328,25.140244,880,37.272727
BFL,851,36.564042,2587,32.895245
BGM,70,62.342857,259,27.027027
...,...,...,...,...
SRQ,990,40.962626,3318,29.837251
STC,38,48.710526,77,49.350649
STL,16803,32.371719,46181,36.385093
STT,1358,46.034610,4171,32.558140
STX,361,32.310249,932,38.733906
SUN,254,36.192913,867,29.296424
SUX,189,53.576720,589,32.088285
SWF,260,42.019231,678,38.348083
SYR,1592,41.640075,5447,29.227097
TLH,957,37.819227,3141,30.468004
TOL,220,42.918182,897,24.526198
TPA,22072,35.625272,63077,34.992152
TRI,631,34.166403,1906,33.105981
TTN,1127,49.741792,2771,40.671238
TUL,4662,34.842557,13701,34.026713
TUS,4884,30.611179,14922,32.730197
TVC,825,36.832727,2660,31.015038
TWF,213,24.849765,805,26.459627
TXK,327,31.978593,918,35.620915
TYR,817,37.842105,2199,37.153251
TYS,2665,40.398124,6754,39.458099
UST,61,41.491803,144,42.361111
VEL,23,61.173913,200,11.500000
VLD,359,30.883008,925,38.810811
VPS,1544,42.673575,4744,32.546374
WRG,236,31.881356,649,36.363636
WYS,58,18.034483,208,27.884615
XNA,3727,42.884626,8963,41.582060
YAK,159,25.930818,650,24.461538
YUM,627,24.473684,1854,33.818770

In [54]:
#Origin Airport vs Departure Delay
ORIGIN_AIRPORT_DEPT_DELAY_METRIC = data.loc[data['DEPARTURE_DELAY']>0,['ORIGIN_AIRPORT','DEPARTURE_DELAY']].groupby(['ORIGIN_AIRPORT']).agg(['count','mean'])
ORIGIN_AIRPORT_DEPT_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['ORIGIN_AIRPORT','DEPARTURE_DELAY']].groupby(['ORIGIN_AIRPORT']).count().rename(columns={"DEPARTURE_DELAY":"TOTAL_FLIGHTS"})



ORIGIN_AIRPORT_DEPT_DELAY_METRIC = pd.merge(ORIGIN_AIRPORT_DEPT_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
ORIGIN_AIRPORT_DEPT_DELAY_METRIC['PERCENTAGE_DELAYED'] = (ORIGIN_AIRPORT_DEPT_DELAY_METRIC.TOTAL_DELAY_COUNT/ORIGIN_AIRPORT_DEPT_DELAY_METRIC.TOTAL_FLIGHTS)*100
ORIGIN_AIRPORT_DEPT_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
ORIGIN_AIRPORT,,,,
ABE,610,44.519672,2236,27.280859
ABI,557,44.254937,2236,24.910555
ABQ,6991,32.059219,18986,36.821869
ABR,140,63.171429,663,21.116139
ABY,204,51.926471,867,23.529412
ACK,207,46.342995,486,42.592593
ACT,397,50.390428,1544,25.712435
ACV,401,51.940150,1270,31.574803
ACY,1209,41.105873,3532,34.229898
ADK,55,27.472727,89,61.797753
ADQ,127,24.543307,437,29.061785
AEX,817,51.711138,3062,26.681907
AGS,703,39.530583,2346,29.965899
AKN,30,13.800000,63,47.619048
ALB,2192,33.233577,7344,29.847495
ALO,121,49.801653,583,20.754717
AMA,1202,37.267055,4086,29.417523
ANC,4493,27.111284,15904,28.250755
APN,93,68.430108,548,16.970803
ASE,1346,52.213224,3290,40.911854
ATL,129846,29.326772,344384,37.703842
ATW,710,40.232394,2769,25.641026
AUS,16239,32.255681,41507,39.123521
AVL,775,44.040000,2685,28.864060
AVP,357,47.535014,1331,26.821938
AZO,331,50.425982,1746,18.957617
BDL,6104,31.983290,18442,33.098362
BET,257,28.591440,880,29.204545
BFL,582,51.618557,2598,22.401848
BGM,55,77.490909,259,21.235521
...,...,...,...,...
SRQ,1103,38.884859,3333,33.093309
STC,28,65.214286,78,35.897436
STL,18261,31.090521,46329,39.415917
STT,1533,45.409654,4301,35.642874
STX,348,33.120690,936,37.179487
SUN,201,42.995025,868,23.156682
SUX,155,55.167742,591,26.226734
SWF,209,49.674641,683,30.600293
SYR,1364,45.090176,5464,24.963397
TLH,800,42.377500,3152,25.380711
TOL,170,46.064706,898,18.930958
TPA,23364,34.903441,63302,36.908786
TRI,490,38.559184,1909,25.667889
TTN,973,54.635149,2784,34.949713
TUL,4299,36.414282,13753,31.258634
TUS,4179,35.439100,14974,27.908375
TVC,622,43.276527,2670,23.295880
TWF,137,27.372263,807,16.976456
TXK,242,38.041322,920,26.304348
TYR,617,44.418152,2201,28.032712
TYS,2270,43.609251,6797,33.397087
UST,71,40.338028,144,49.305556
VEL,10,133.600000,200,5.000000
VLD,208,44.596154,927,22.437972
VPS,1358,46.550810,4770,28.469602
WRG,194,36.067010,653,29.709035
WYS,41,24.243902,208,19.711538
XNA,2783,51.078333,8997,30.932533
YAK,128,30.210938,657,19.482496
YUM,339,39.911504,1854,18.284790

In [55]:
#Destination Airport vs Departure Delay
DEST_AIRPORT_DEPT_DELAY_METRIC = data.loc[data['DEPARTURE_DELAY']>0,['DESTINATION_AIRPORT','DEPARTURE_DELAY']].groupby(['DESTINATION_AIRPORT']).agg(['count','mean'])
DEST_AIRPORT_DEPT_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['DESTINATION_AIRPORT','DEPARTURE_DELAY']].groupby(['DESTINATION_AIRPORT']).count().rename(columns={"DEPARTURE_DELAY":"TOTAL_FLIGHTS"})



DEST_AIRPORT_DEPT_DELAY_METRIC = pd.merge(DEST_AIRPORT_DEPT_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
DEST_AIRPORT_DEPT_DELAY_METRIC['PERCENTAGE_DELAYED'] = (DEST_AIRPORT_DEPT_DELAY_METRIC.TOTAL_DELAY_COUNT/DEST_AIRPORT_DEPT_DELAY_METRIC.TOTAL_FLIGHTS)*100
DEST_AIRPORT_DEPT_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
DESTINATION_AIRPORT,,,,
ABE,686,37.513120,2229,30.776133
ABI,742,31.962264,2236,33.184258
ABQ,8417,27.856837,18996,44.309328
ABR,134,32.417910,665,20.150376
ABY,284,38.876761,869,32.681243
ACK,136,43.205882,490,27.755102
ACT,563,43.772647,1543,36.487362
ACV,429,45.407925,1282,33.463339
ACY,1462,40.639535,3535,41.357850
ADK,21,23.523810,89,23.595506
ADQ,82,20.609756,448,18.303571
AEX,1020,33.952941,3068,33.246415
AGS,763,33.913499,2349,32.481907
AKN,16,19.312500,63,25.396825
ALB,3258,30.846225,7351,44.320501
ALO,206,41.378641,588,35.034014
AMA,1554,28.595238,4094,37.957987
ANC,6115,24.371545,15853,38.573141
APN,101,62.118812,556,18.165468
ASE,1687,38.201541,3444,48.983740
ATL,110754,34.136076,344280,32.169746
ATW,742,35.572776,2770,26.787004
AUS,17446,32.780924,41578,41.959690
AVL,874,38.517162,2706,32.298596
AVP,452,38.451327,1333,33.908477
AZO,554,33.855596,1755,31.566952
BDL,8039,32.968902,18450,43.571816
BET,212,28.500000,887,23.900789
BFL,786,39.162850,2601,30.219146
BGM,66,41.712121,260,25.384615
...,...,...,...,...
SRQ,1194,29.384422,3340,35.748503
STC,41,42.097561,77,53.246753
STL,18497,29.881873,46384,39.877975
STT,1689,35.483718,4327,39.033973
STX,368,28.866848,936,39.316239
SUN,263,31.745247,953,27.597062
SUX,215,37.102326,593,36.256324
SWF,282,35.336879,682,41.348974
SYR,1988,37.165996,5484,36.250912
TLH,1055,36.300474,3157,33.417802
TOL,275,31.400000,903,30.454042
TPA,25990,31.224740,63346,41.028636
TRI,544,30.628676,1912,28.451883
TTN,1148,52.695122,2772,41.414141
TUL,5575,31.358027,13779,40.460120
TUS,5892,31.841310,14991,39.303582
TVC,839,33.069130,2675,31.364486
TWF,101,31.673267,811,12.453761
TXK,310,26.474194,927,33.441208
TYR,696,36.352011,2209,31.507469
TYS,2518,39.417792,6782,37.127691
UST,67,41.388060,149,44.966443
VEL,7,24.714286,201,3.482587
VLD,290,34.717241,927,31.283711
VPS,1649,33.510612,4774,34.541265
WRG,214,38.289720,657,32.572298
WYS,27,19.666667,208,12.980769
XNA,3392,36.728774,9032,37.555359
YAK,189,24.439153,653,28.943338
YUM,396,32.323232,1861,21.278882

In [56]:
#Destination Airport vs Arrival Delay
DEST_AIRPORT_ARR_DELAY_METRIC = data.loc[data['ARRIVAL_DELAY']>0,['DESTINATION_AIRPORT','ARRIVAL_DELAY']].groupby(['DESTINATION_AIRPORT']).agg(['count','mean'])
DEST_AIRPORT_ARR_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['DESTINATION_AIRPORT','ARRIVAL_DELAY']].groupby(['DESTINATION_AIRPORT']).count().rename(columns={"ARRIVAL_DELAY":"TOTAL_FLIGHTS"})



DEST_AIRPORT_ARR_DELAY_METRIC = pd.merge(DEST_AIRPORT_ARR_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
DEST_AIRPORT_ARR_DELAY_METRIC['PERCENTAGE_DELAYED'] = (DEST_AIRPORT_ARR_DELAY_METRIC.TOTAL_DELAY_COUNT/DEST_AIRPORT_ARR_DELAY_METRIC.TOTAL_FLIGHTS)*100
DEST_AIRPORT_ARR_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
DESTINATION_AIRPORT,,,,
ABE,840,31.459524,2220,37.837838
ABI,748,31.830214,2224,33.633094
ABQ,7876,28.017395,18953,41.555427
ABR,163,24.453988,657,24.809741
ABY,347,34.138329,864,40.162037
ACK,152,41.348684,487,31.211499
ACT,646,38.990712,1541,41.920831
ACV,540,36.881481,1267,42.620363
ACY,1599,37.495310,3530,45.297450
ADK,31,18.129032,89,34.831461
ADQ,130,16.984615,437,29.748284
AEX,1196,30.657191,3055,39.148936
AGS,881,30.452894,2347,37.537282
AKN,26,15.346154,63,41.269841
ALB,2944,31.756114,7341,40.103528
ALO,211,41.616114,585,36.068376
AMA,1718,27.261350,4071,42.200933
ANC,6247,24.352009,15819,39.490486
APN,129,49.062016,549,23.497268
ASE,1775,36.967324,3260,54.447853
ATL,105603,35.611308,343076,30.781226
ATW,1025,28.183415,2763,37.097358
AUS,16732,33.368396,41445,40.371577
AVL,987,34.448835,2691,36.677815
AVP,603,32.922056,1325,45.509434
AZO,514,36.130350,1743,29.489386
BDL,7211,33.819720,18404,39.181700
BET,319,21.871473,879,36.291240
BFL,1049,30.252622,2587,40.548898
BGM,89,30.887640,258,34.496124
...,...,...,...,...
SRQ,1101,31.126249,3336,33.003597
STC,48,41.208333,77,62.337662
STL,16807,30.976795,46273,36.321397
STT,1623,36.191004,4306,37.691593
STX,392,27.696429,933,42.015005
SUN,300,27.906667,854,35.128806
SUX,193,42.626943,591,32.656514
SWF,272,33.525735,680,40.000000
SYR,2105,35.327791,5475,38.447489
TLH,1114,33.933573,3149,35.376310
TOL,243,37.329218,901,26.970033
TPA,23083,34.051077,63157,36.548601
TRI,592,27.684122,1912,30.962343
TTN,1339,47.804332,2761,48.496921
TUL,5600,31.026429,13748,40.733198
TUS,6103,30.320826,14956,40.806365
TVC,850,34.183529,2666,31.882971
TWF,337,16.670623,806,41.811414
TXK,352,25.536932,915,38.469945
TYR,880,31.768182,2199,40.018190
TYS,3046,35.785620,6764,45.032525
UST,54,39.129630,146,36.986301
VEL,19,10.052632,197,9.644670
VLD,385,27.893506,921,41.802389
VPS,1803,31.669440,4743,38.013915
WRG,259,32.019305,652,39.723926
WYS,119,10.336134,207,57.487923
XNA,3920,33.655867,8986,43.623414
YAK,224,23.562500,652,34.355828
YUM,677,22.391433,1856,36.476293

In [57]:
#Day Of The Week vs Arrival Delay
DAY_OF_WEEK_ARR_DELAY_METRIC = data.loc[data['ARRIVAL_DELAY']>0,['DAY_OF_WEEK','ARRIVAL_DELAY']].groupby(['DAY_OF_WEEK']).agg(['count','mean'])
DAY_OF_WEEK_ARR_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['DAY_OF_WEEK','ARRIVAL_DELAY']].groupby(['DAY_OF_WEEK']).count().rename(columns={"ARRIVAL_DELAY":"TOTAL_FLIGHTS"})



DAY_OF_WEEK_ARR_DELAY_METRIC = pd.merge(DAY_OF_WEEK_ARR_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
DAY_OF_WEEK_ARR_DELAY_METRIC['PERCENTAGE_DELAYED'] = (DAY_OF_WEEK_ARR_DELAY_METRIC.TOTAL_DELAY_COUNT/DAY_OF_WEEK_ARR_DELAY_METRIC.TOTAL_FLIGHTS)*100
DAY_OF_WEEK_ARR_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
DAY_OF_WEEK,,,,
1,297746,36.757303,775714,38.383476
2,280846,34.471689,763813,36.768947
3,287420,32.302832,778658,36.912226
4,309277,33.351119,775433,39.884426
5,296082,31.237350,770324,38.436035
6,207521,32.363587,627502,33.070970
7,266754,34.134690,739686,36.063140

In [58]:
#Day Of The Week vs Departure Delay
DAY_OF_WEEK_DEPT_DELAY_METRIC = data.loc[data['DEPARTURE_DELAY']>0,['DAY_OF_WEEK','DEPARTURE_DELAY']].groupby(['DAY_OF_WEEK']).agg(['count','mean'])
DAY_OF_WEEK_DEPT_DELAY_METRIC.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


PERCENTAGE_FLIGHTS_DELAYED = data.loc[:,['DAY_OF_WEEK','DEPARTURE_DELAY']].groupby(['DAY_OF_WEEK']).count().rename(columns={"DEPARTURE_DELAY":"TOTAL_FLIGHTS"})



DAY_OF_WEEK_DEPT_DELAY_METRIC = pd.merge(DAY_OF_WEEK_DEPT_DELAY_METRIC,PERCENTAGE_FLIGHTS_DELAYED, how = 'inner', left_index = True, right_index = True )
DAY_OF_WEEK_DEPT_DELAY_METRIC['PERCENTAGE_DELAYED'] = (DAY_OF_WEEK_DEPT_DELAY_METRIC.TOTAL_DELAY_COUNT/DAY_OF_WEEK_DEPT_DELAY_METRIC.TOTAL_FLIGHTS)*100
DAY_OF_WEEK_DEPT_DELAY_METRIC
#AIRPORT_ARR_DELAY_METRIC.to_csv(path_or_buf='C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis',mode = 'w',sep=',')

,TOTAL_DELAY_COUNT,MEAN_DELAY_COUNT,TOTAL_FLIGHTS,PERCENTAGE_DELAYED
DAY_OF_WEEK,,,,
1,305229,35.946725,779131,39.175569
2,281252,34.420786,766349,36.700250
3,285819,32.469643,780921,36.600245
4,307950,32.990989,778126,39.575853
5,299475,31.064727,772459,38.769048
6,219884,31.518110,629889,34.908373
7,280907,32.917051,742225,37.846610

In [59]:
# Month Vs Arrival Delay

#data.index = data['FLIGHT_DATE']
MONTHWISE_ARR_DELAY_METRICS = data.loc[data['ARRIVAL_DELAY']>0,['FLIGHT_DATE','ARRIVAL_DELAY']].groupby(pd.TimeGrouper(freq='M')).agg(['count','mean'])
MONTHWISE_ARR_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


MONTHLY_TOTAL_FLIGHTS = data.loc[:,['ARRIVAL_DELAY']].groupby(pd.TimeGrouper(freq='M')).agg(['count'])
MONTHLY_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']


MONTHWISE_ARR_DELAY_METRICS = pd.merge(MONTHWISE_ARR_DELAY_METRICS,MONTHLY_TOTAL_FLIGHTS,how = 'inner',left_index = True, right_index=True)
MONTHWISE_ARR_DELAY_METRICS['PERCENTAGE_DELAYS'] = (MONTHWISE_ARR_DELAY_METRICS.TOTAL_DELAY_COUNT/MONTHWISE_ARR_DELAY_METRICS.TOTAL_FLIGHTS)*100
MONTHWISE_ARR_DELAY_METRICS

/Users/vsanjeev/anaconda/envs/Py27/lib/python2.7/site-packages/ipykernel_launcher.py:4: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  after removing the cwd from sys.path.

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Int64Index'

In [60]:
# Month Vs Departure Delay

#data.index = data['FLIGHT_DATE']
MONTHWISE_DEPT_DELAY_METRICS = data.loc[data['DEPARTURE_DELAY']>0,['FLIGHT_DATE','DEPARTURE_DELAY']].groupby(pd.TimeGrouper(freq='M')).agg(['count','mean'])
MONTHWISE_DEPT_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']


MONTHLY_TOTAL_FLIGHTS = data.loc[:,['DEPARTURE_DELAY']].groupby(pd.TimeGrouper(freq='M')).agg(['count'])
MONTHLY_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']


MONTHWISE_DEPT_DELAY_METRICS = pd.merge(MONTHWISE_DEPT_DELAY_METRICS,MONTHLY_TOTAL_FLIGHTS,how = 'inner',left_index = True, right_index=True)
MONTHWISE_DEPT_DELAY_METRICS['PERCENTAGE_DELAYS'] = (MONTHWISE_DEPT_DELAY_METRICS.TOTAL_DELAY_COUNT/MONTHWISE_DEPT_DELAY_METRICS.TOTAL_FLIGHTS)*100
MONTHWISE_DEPT_DELAY_METRICS

/Users/vsanjeev/anaconda/envs/Py27/lib/python2.7/site-packages/ipykernel_launcher.py:4: FutureWarning: pd.TimeGrouper is deprecated and will be removed; Please use pd.Grouper(freq=...)
  after removing the cwd from sys.path.

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Int64Index'

In [ ]:
data

In [ ]:
# State Vs Arrival Delay(Origin Airport)
STATE_ARR_DELAY_METRICS = pd.merge(data.loc[data['ARRIVAL_DELAY']>0,['ORIGIN_AIRPORT','ARRIVAL_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']],how='outer',left_on =['ORIGIN_AIRPORT'],right_on=['IATA_CODE'])
STATE_ARR_DELAY_METRICS = STATE_ARR_DELAY_METRICS.loc[:,['STATE','ARRIVAL_DELAY']].groupby(['STATE']).agg(['count','mean'])
STATE_ARR_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']

STATE_TOTAL_FLIGHTS = pd.merge(data.loc[:,['ORIGIN_AIRPORT','ARRIVAL_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']], how='outer',left_on =['ORIGIN_AIRPORT'],right_on=['IATA_CODE'])
STATE_TOTAL_FLIGHTS = STATE_TOTAL_FLIGHTS.loc[:,['STATE','ARRIVAL_DELAY']].groupby(['STATE']).agg(['count'])
STATE_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']
STATE_TOTAL_FLIGHTS

STATE_ARR_DELAY_METRICS = pd.merge(STATE_ARR_DELAY_METRICS,STATE_TOTAL_FLIGHTS, how = 'inner', left_index=True, right_index=True)
STATE_ARR_DELAY_METRICS['PERCENTAGE_DELAYS'] = (STATE_ARR_DELAY_METRICS.TOTAL_DELAY_COUNT/STATE_ARR_DELAY_METRICS.TOTAL_FLIGHTS)*100
STATE_ARR_DELAY_METRICS

In [ ]:
# State Vs Departure Delay(Origin Airport)
STATE_DEPT_DELAY_METRICS = pd.merge(data.loc[data['DEPARTURE_DELAY']>0,['ORIGIN_AIRPORT','DEPARTURE_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']],how='outer',left_on =['ORIGIN_AIRPORT'],right_on=['IATA_CODE'])
STATE_DEPT_DELAY_METRICS = STATE_DEPT_DELAY_METRICS.loc[:,['STATE','DEPARTURE_DELAY']].groupby(['STATE']).agg(['count','mean'])
STATE_DEPT_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']

STATE_TOTAL_FLIGHTS = pd.merge(data.loc[:,['ORIGIN_AIRPORT','DEPARTURE_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']], how='outer',left_on =['ORIGIN_AIRPORT'],right_on=['IATA_CODE'])
STATE_TOTAL_FLIGHTS = STATE_TOTAL_FLIGHTS.loc[:,['STATE','DEPARTURE_DELAY']].groupby(['STATE']).agg(['count'])
STATE_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']
STATE_TOTAL_FLIGHTS

STATE_DEPT_DELAY_METRICS = pd.merge(STATE_DEPT_DELAY_METRICS,STATE_TOTAL_FLIGHTS, how = 'inner', left_index=True, right_index=True)
STATE_DEPT_DELAY_METRICS['PERCENTAGE_DELAYS'] = (STATE_DEPT_DELAY_METRICS.TOTAL_DELAY_COUNT/STATE_DEPT_DELAY_METRICS.TOTAL_FLIGHTS)*100
STATE_DEPT_DELAY_METRICS

In [ ]:
# State Vs Departure Delay(Destination Airport)

STATE_DEPT_DELAY_METRICS = pd.merge(data.loc[data['DEPARTURE_DELAY']>0,['DESTINATION_AIRPORT','DEPARTURE_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']],how='outer',left_on =['DESTINATION_AIRPORT'],right_on=['IATA_CODE'])
STATE_DEPT_DELAY_METRICS = STATE_DEPT_DELAY_METRICS.loc[:,['STATE','DEPARTURE_DELAY']].groupby(['STATE']).agg(['count','mean'])
STATE_DEPT_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']

STATE_TOTAL_FLIGHTS = pd.merge(data.loc[:,['DESTINATION_AIRPORT','DEPARTURE_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']], how='outer',left_on =['DESTINATION_AIRPORT'],right_on=['IATA_CODE'])
STATE_TOTAL_FLIGHTS = STATE_TOTAL_FLIGHTS.loc[:,['STATE','DEPARTURE_DELAY']].groupby(['STATE']).agg(['count'])
STATE_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']
STATE_TOTAL_FLIGHTS

STATE_DEPT_DELAY_METRICS = pd.merge(STATE_DEPT_DELAY_METRICS,STATE_TOTAL_FLIGHTS, how = 'inner', left_index=True, right_index=True)
STATE_DEPT_DELAY_METRICS['PERCENTAGE_DELAYS'] = (STATE_DEPT_DELAY_METRICS.TOTAL_DELAY_COUNT/STATE_DEPT_DELAY_METRICS.TOTAL_FLIGHTS)*100
STATE_DEPT_DELAY_METRICS

In [ ]:
# State Vs Arrival Delay(Destination Airport)

STATE_ARR_DELAY_METRICS = pd.merge(data.loc[data['ARRIVAL_DELAY']>0,['DESTINATION_AIRPORT','ARRIVAL_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']],how='outer',left_on =['DESTINATION_AIRPORT'],right_on=['IATA_CODE'])
STATE_ARR_DELAY_METRICS = STATE_ARR_DELAY_METRICS.loc[:,['STATE','ARRIVAL_DELAY']].groupby(['STATE']).agg(['count','mean'])
STATE_ARR_DELAY_METRICS.columns = ['TOTAL_DELAY_COUNT','MEAN_DELAY_COUNT']

STATE_TOTAL_FLIGHTS = pd.merge(data.loc[:,['DESTINATION_AIRPORT','ARRIVAL_DELAY']],airport_data.loc[:,['IATA_CODE','STATE']], how='outer',left_on =['DESTINATION_AIRPORT'],right_on=['IATA_CODE'])
STATE_TOTAL_FLIGHTS = STATE_TOTAL_FLIGHTS.loc[:,['STATE','ARRIVAL_DELAY']].groupby(['STATE']).agg(['count'])
STATE_TOTAL_FLIGHTS.columns = ['TOTAL_FLIGHTS']
STATE_TOTAL_FLIGHTS

STATE_ARR_DELAY_METRICS = pd.merge(STATE_ARR_DELAY_METRICS,STATE_TOTAL_FLIGHTS, how = 'inner', left_index=True, right_index=True)
STATE_ARR_DELAY_METRICS['PERCENTAGE_DELAYS'] = (STATE_ARR_DELAY_METRICS.TOTAL_DELAY_COUNT/STATE_ARR_DELAY_METRICS.TOTAL_FLIGHTS)*100
#STATE_ARR_DELAY_METRICS.to_csv ('C:\\Users\\rashm\\PycharmProjects\\DataProgrammingProject\\ExploratoryAnalysis\\STATE_ARR_DELAY_METRICS_BY_DESTINATION.csv')

In [ ]:
print "max:%s" %(data.DISTANCE.max())
print "min:%s" %(data.DISTANCE.min())

In [ ]:
data['DISTANCE_BINS']= pd.qcut(data.DISTANCE,11)
data.head()
test = data.loc[:,['DISTANCE','ARRIVAL_DELAY']].groupby(data['DISTANCE_BINS']).mean()
test

In [ ]:
data.ARRIVAL_TIME.unique()